services:

  # -------------------------------
  discovery-service:
    image: discovery-service:latest
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-net

  # -------------------------------
  db-category:
    image: postgres:16
    environment:
      POSTGRES_DB: db_category
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net
  
  category-service:
    image: category-service:latest
    build:
      context: ./category-service
    ports:
      - "8001:8001"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-category:5432/db_category
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

  # -------------------------------
  db-order:
    image: postgres:16
    environment:
      POSTGRES_DB: db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net
  
  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8003:8003"
    depends_on:
      - discovery-service
      - currency-service
      - product-service
      - db-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-order:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

  # -------------------------------
  db-sport:
    image: postgres:16
    environment:
      POSTGRES_DB: db_sport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net
  
  sport-service:
    image: sport-service:latest
    build:
      context: ./sport-service
    ports:
      - "8005:8005"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-sport:5432/db_sport
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

    # -------------------------------
  db-team:
    image: postgres:16
    environment:
      POSTGRES_DB: db_team
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net
  
  team-service:
    image: team-service:latest
    build:
      context: ./team-service
    ports:
      - "8006:8006"
    depends_on:
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-team:5432/db_team
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net


  # -------------------------------
  db-currency:
    image: postgres:16
    environment:
      POSTGRES_DB: db_currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net

  currency-service:
    image: currency-service:latest
    build:
      context: ./currency-service
    depends_on:
      - discovery-service
      - db-currency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-currency:5432/db_currency
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

  # -------------------------------
  db-product:
    image: postgres:16
    environment:
      POSTGRES_DB: db_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net

  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    ports:
      - "8004:8004"
    depends_on:
      - discovery-service
      - db-product
      - currency-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-product:5432/db_product
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

  # -------------------------------

  db-user:
    image: postgres:16
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-net

  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
    ports:
      - "8010:8010"
    depends_on:
      - discovery-service
      - db-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/db_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

  # -------------------------------


  gateway-service:
    image: gateway-service:latest
    build:
      context: ./gateway-service
    ports:
      - "8765:8765"
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    networks:
      - spring-net

# -------------------------------
networks:
  spring-net:
    driver: bridge
